<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Evaluacion', 'doctrine');

/**
 * BaseEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_corto
 * @property Doctrine_Collection $Convocatorias
 * @property Doctrine_Collection $ConvocatoriaEvaluaciones
 * @property Doctrine_Collection $ConvocatoriaRequerimientoEvaluaciones
 * 
 * @method integer             getId()                                    Returns the current record's "id" value
 * @method string              getNombre()                                Returns the current record's "nombre" value
 * @method string              getNombreCorto()                           Returns the current record's "nombre_corto" value
 * @method Doctrine_Collection getConvocatorias()                         Returns the current record's "Convocatorias" collection
 * @method Doctrine_Collection getConvocatoriaEvaluaciones()              Returns the current record's "ConvocatoriaEvaluaciones" collection
 * @method Doctrine_Collection getConvocatoriaRequerimientoEvaluaciones() Returns the current record's "ConvocatoriaRequerimientoEvaluaciones" collection
 * @method Evaluacion          setId()                                    Sets the current record's "id" value
 * @method Evaluacion          setNombre()                                Sets the current record's "nombre" value
 * @method Evaluacion          setNombreCorto()                           Sets the current record's "nombre_corto" value
 * @method Evaluacion          setConvocatorias()                         Sets the current record's "Convocatorias" collection
 * @method Evaluacion          setConvocatoriaEvaluaciones()              Sets the current record's "ConvocatoriaEvaluaciones" collection
 * @method Evaluacion          setConvocatoriaRequerimientoEvaluaciones() Sets the current record's "ConvocatoriaRequerimientoEvaluaciones" collection
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evaluacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('nombre_corto', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 128,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Convocatoria as Convocatorias', array(
             'refClass' => 'ConvocatoriaEvaluacion',
             'local' => 'evaluacion_id',
             'foreign' => 'convocatoria_id'));

        $this->hasMany('ConvocatoriaEvaluacion as ConvocatoriaEvaluaciones', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $this->hasMany('ConvocatoriaRequerimientoEvaluacion as ConvocatoriaRequerimientoEvaluaciones', array(
             'local' => 'id',
             'foreign' => 'evaluacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}