<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DocumentacionVolumen', 'doctrine');

/**
 * BaseDocumentacionVolumen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $plantilla_id
 * @property Doctrine_Collection $Documentaciones
 * @property DocumentacionPlantilla $DocumentacionPlantilla
 * 
 * @method integer                getId()                     Returns the current record's "id" value
 * @method integer                getPlantillaId()            Returns the current record's "plantilla_id" value
 * @method Doctrine_Collection    getDocumentaciones()        Returns the current record's "Documentaciones" collection
 * @method DocumentacionPlantilla getDocumentacionPlantilla() Returns the current record's "DocumentacionPlantilla" value
 * @method DocumentacionVolumen   setId()                     Sets the current record's "id" value
 * @method DocumentacionVolumen   setPlantillaId()            Sets the current record's "plantilla_id" value
 * @method DocumentacionVolumen   setDocumentaciones()        Sets the current record's "Documentaciones" collection
 * @method DocumentacionVolumen   setDocumentacionPlantilla() Sets the current record's "DocumentacionPlantilla" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentacionVolumen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentacion_volumen');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('plantilla_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Documentacion as Documentaciones', array(
             'local' => 'id',
             'foreign' => 'volumen_id'));

        $this->hasOne('DocumentacionPlantilla', array(
             'local' => 'plantilla_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}