<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Plantilla', 'doctrine');

/**
 * BasePlantilla
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property clob $redaccion
 * @property clob $types
 * 
 * @method integer   getId()        Returns the current record's "id" value
 * @method string    getNombre()    Returns the current record's "nombre" value
 * @method clob      getRedaccion() Returns the current record's "redaccion" value
 * @method clob      getTypes()     Returns the current record's "types" value
 * @method Plantilla setId()        Sets the current record's "id" value
 * @method Plantilla setNombre()    Sets the current record's "nombre" value
 * @method Plantilla setRedaccion() Sets the current record's "redaccion" value
 * @method Plantilla setTypes()     Sets the current record's "types" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlantilla extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('plantilla');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('redaccion', 'clob', null, array(
             'type' => 'clob',
             'fixed' => 0,
             'notnull' => true,
             'default' => '',
             ));
        $this->hasColumn('types', 'clob', null, array(
             'type' => 'clob',
             'fixed' => 0,
             'notnull' => true,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}