<?php

/**
 * BaseUsuarioGrupoConvocatoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $grupo_id
 * @property integer $convocatoria_id
 * @property sfGuardUser $Usuario
 * @property Grupo $Grupo
 * @property Convocatoria $Convocatoria
 * 
 * @method integer                  getUserId()          Returns the current record's "user_id" value
 * @method integer                  getGrupoId()         Returns the current record's "grupo_id" value
 * @method integer                  getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method sfGuardUser              getUsuario()         Returns the current record's "Usuario" value
 * @method Grupo                    getGrupo()           Returns the current record's "Grupo" value
 * @method Convocatoria             getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method UsuarioGrupoConvocatoria setUserId()          Sets the current record's "user_id" value
 * @method UsuarioGrupoConvocatoria setGrupoId()         Sets the current record's "grupo_id" value
 * @method UsuarioGrupoConvocatoria setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method UsuarioGrupoConvocatoria setUsuario()         Sets the current record's "Usuario" value
 * @method UsuarioGrupoConvocatoria setGrupo()           Sets the current record's "Grupo" value
 * @method UsuarioGrupoConvocatoria setConvocatoria()    Sets the current record's "Convocatoria" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioGrupoConvocatoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_grupo_convocatoria');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('grupo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Usuario', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Grupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}