<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cargo', 'doctrine');

/**
 * BaseCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cargo
 * @property string $encargado
 * @property string $email
 * @property boolean $activo
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method string  getCargo()     Returns the current record's "cargo" value
 * @method string  getEncargado() Returns the current record's "encargado" value
 * @method string  getEmail()     Returns the current record's "email" value
 * @method boolean getActivo()    Returns the current record's "activo" value
 * @method Cargo   setId()        Sets the current record's "id" value
 * @method Cargo   setCargo()     Sets the current record's "cargo" value
 * @method Cargo   setEncargado() Sets the current record's "encargado" value
 * @method Cargo   setEmail()     Sets the current record's "email" value
 * @method Cargo   setActivo()    Sets the current record's "activo" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cargo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cargo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('encargado', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('activo', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}