<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaDocumento', 'doctrine');

/**
 * BaseConvocatoriaDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $documento_id
 * @property integer $numero_orden
 * @property Convocatoria $Convocatoria
 * @property Documento $Documento
 * 
 * @method integer               getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method integer               getDocumentoId()     Returns the current record's "documento_id" value
 * @method integer               getNumeroOrden()     Returns the current record's "numero_orden" value
 * @method Convocatoria          getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method Documento             getDocumento()       Returns the current record's "Documento" value
 * @method ConvocatoriaDocumento setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaDocumento setDocumentoId()     Sets the current record's "documento_id" value
 * @method ConvocatoriaDocumento setNumeroOrden()     Sets the current record's "numero_orden" value
 * @method ConvocatoriaDocumento setConvocatoria()    Sets the current record's "Convocatoria" value
 * @method ConvocatoriaDocumento setDocumento()       Sets the current record's "Documento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_documento');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('documento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero_orden', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Documento', array(
             'local' => 'documento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}