<?php

/**
 * BaseGrupoPermiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $grupo_id
 * @property integer $permiso_id
 * @property Grupo $Grupo
 * @property Permiso $Permiso
 * 
 * @method integer      getGrupoId()    Returns the current record's "grupo_id" value
 * @method integer      getPermisoId()  Returns the current record's "permiso_id" value
 * @method Grupo        getGrupo()      Returns the current record's "Grupo" value
 * @method Permiso      getPermiso()    Returns the current record's "Permiso" value
 * @method GrupoPermiso setGrupoId()    Sets the current record's "grupo_id" value
 * @method GrupoPermiso setPermisoId()  Sets the current record's "permiso_id" value
 * @method GrupoPermiso setGrupo()      Sets the current record's "Grupo" value
 * @method GrupoPermiso setPermiso()    Sets the current record's "Permiso" value
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupoPermiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo_permiso');
        $this->hasColumn('grupo_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('permiso_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Grupo', array(
             'local' => 'grupo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Permiso', array(
             'local' => 'permiso_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}