<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulacionRequerimiento', 'doctrine');

/**
 * BasePostulacionRequerimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulacion_id
 * @property integer $requerimiento_id
 * @property Postulacion $Postulacion
 * @property Requerimiento $Requerimiento
 * 
 * @method integer                  getPostulacionId()    Returns the current record's "postulacion_id" value
 * @method integer                  getRequerimientoId()  Returns the current record's "requerimiento_id" value
 * @method Postulacion              getPostulacion()      Returns the current record's "Postulacion" value
 * @method Requerimiento            getRequerimiento()    Returns the current record's "Requerimiento" value
 * @method PostulacionRequerimiento setPostulacionId()    Sets the current record's "postulacion_id" value
 * @method PostulacionRequerimiento setRequerimientoId()  Sets the current record's "requerimiento_id" value
 * @method PostulacionRequerimiento setPostulacion()      Sets the current record's "Postulacion" value
 * @method PostulacionRequerimiento setRequerimiento()    Sets the current record's "Requerimiento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulacionRequerimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulacion_requerimiento');
        $this->hasColumn('postulacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requerimiento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulacion', array(
             'local' => 'postulacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Requerimiento', array(
             'local' => 'requerimiento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}