<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaRequerimientoEvaluacion', 'doctrine');

/**
 * BaseConvocatoriaRequerimientoEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $requerimiento_id
 * @property integer $evaluacion_id
 * @property Convocatoria $Convocatoria
 * @property Requerimiento $Requerimiento
 * 
 * @method integer                             getConvocatoriaId()   Returns the current record's "convocatoria_id" value
 * @method integer                             getRequerimientoId()  Returns the current record's "requerimiento_id" value
 * @method integer                             getEvaluacionId()     Returns the current record's "evaluacion_id" value
 * @method Convocatoria                        getConvocatoria()     Returns the current record's "Convocatoria" value
 * @method Requerimiento                       getRequerimiento()    Returns the current record's "Requerimiento" value
 * @method ConvocatoriaRequerimientoEvaluacion setConvocatoriaId()   Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaRequerimientoEvaluacion setRequerimientoId()  Sets the current record's "requerimiento_id" value
 * @method ConvocatoriaRequerimientoEvaluacion setEvaluacionId()     Sets the current record's "evaluacion_id" value
 * @method ConvocatoriaRequerimientoEvaluacion setConvocatoria()     Sets the current record's "Convocatoria" value
 * @method ConvocatoriaRequerimientoEvaluacion setRequerimiento()    Sets the current record's "Requerimiento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaRequerimientoEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_requerimiento_evaluacion');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requerimiento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('evaluacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id'));

        $this->hasOne('Requerimiento', array(
             'local' => 'requerimiento_id',
             'foreign' => 'id'));
    }
}