<?php

/**
 * BasePermiso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $GrupoPermiso
 * 
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getDescripcion()  Returns the current record's "descripcion" value
 * @method Doctrine_Collection getGrupoPermiso() Returns the current record's "GrupoPermiso" collection
 * @method Permiso             setNombre()       Sets the current record's "nombre" value
 * @method Permiso             setDescripcion()  Sets the current record's "descripcion" value
 * @method Permiso             setGrupoPermiso() Sets the current record's "GrupoPermiso" collection
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePermiso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('permiso');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('GrupoPermiso', array(
             'local' => 'id',
             'foreign' => 'permiso_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}