<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulanteDocumento', 'doctrine');

/**
 * BasePostulanteDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulante_id
 * @property integer $documento_id
 * @property Postulante $Postulante
 * @property Documento $Documento
 * 
 * @method integer             getPostulanteId()  Returns the current record's "postulante_id" value
 * @method integer             getDocumentoId()   Returns the current record's "documento_id" value
 * @method Postulante          getPostulante()    Returns the current record's "Postulante" value
 * @method Documento           getDocumento()     Returns the current record's "Documento" value
 * @method PostulanteDocumento setPostulanteId()  Sets the current record's "postulante_id" value
 * @method PostulanteDocumento setDocumentoId()   Sets the current record's "documento_id" value
 * @method PostulanteDocumento setPostulante()    Sets the current record's "Postulante" value
 * @method PostulanteDocumento setDocumento()     Sets the current record's "Documento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulanteDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulante_documento');
        $this->hasColumn('postulante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('documento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulante', array(
             'local' => 'postulante_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Documento', array(
             'local' => 'documento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}