<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaRedaccion', 'doctrine');

/**
 * BaseConvocatoriaRedaccion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $numero_enmienda
 * @property clob $redaccion
 * @property Convocatoria $Convocatoria
 * 
 * @method integer               getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method integer               getNumeroEnmienda()  Returns the current record's "numero_enmienda" value
 * @method clob                  getRedaccion()       Returns the current record's "redaccion" value
 * @method Convocatoria          getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method ConvocatoriaRedaccion setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaRedaccion setNumeroEnmienda()  Sets the current record's "numero_enmienda" value
 * @method ConvocatoriaRedaccion setRedaccion()       Sets the current record's "redaccion" value
 * @method ConvocatoriaRedaccion setConvocatoria()    Sets the current record's "Convocatoria" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaRedaccion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_redaccion');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero_enmienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('redaccion', 'clob', null, array(
             'type' => 'clob',
             'fixed' => 0,
             'notnull' => true,
             'default' => '',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}