<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Requerimiento', 'doctrine');

/**
 * BaseRequerimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $nombre
 * @property string $texto
 * @property integer $horas_academicas
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method string        getCodigo()           Returns the current record's "codigo" value
 * @method string        getNombre()           Returns the current record's "nombre" value
 * @method string        getTexto()            Returns the current record's "texto" value
 * @method integer       getHorasAcademicas()  Returns the current record's "horas_academicas" value
 * @method Requerimiento setId()               Sets the current record's "id" value
 * @method Requerimiento setCodigo()           Sets the current record's "codigo" value
 * @method Requerimiento setNombre()           Sets the current record's "nombre" value
 * @method Requerimiento setTexto()            Sets the current record's "texto" value
 * @method Requerimiento setHorasAcademicas()  Sets the current record's "horas_academicas" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequerimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('requerimiento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('horas_academicas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}