<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaEvento', 'doctrine');

/**
 * BaseConvocatoriaEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $evento_id
 * @property timestamp $fecha
 * @property Convocatoria $Convocatoria
 * @property Evento $Evento
 * 
 * @method integer            getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method integer            getEventoId()        Returns the current record's "evento_id" value
 * @method timestamp          getFecha()           Returns the current record's "fecha" value
 * @method Convocatoria       getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method Evento             getEvento()          Returns the current record's "Evento" value
 * @method ConvocatoriaEvento setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaEvento setEventoId()        Sets the current record's "evento_id" value
 * @method ConvocatoriaEvento setFecha()           Sets the current record's "fecha" value
 * @method ConvocatoriaEvento setConvocatoria()    Sets the current record's "Convocatoria" value
 * @method ConvocatoriaEvento setEvento()          Sets the current record's "Evento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_evento');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('evento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'notnull' => true,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id'));

        $this->hasOne('Evento', array(
             'local' => 'evento_id',
             'foreign' => 'id'));
    }
}