<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cargo', 'doctrine');

/**
 * BaseCargo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $cargo
 * @property Doctrine_Collection $Encargados
 * @property Doctrine_Collection $Convocatorias
 * @property Doctrine_Collection $ConvocatoriaCargos
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getCargo()              Returns the current record's "cargo" value
 * @method Doctrine_Collection getEncargados()         Returns the current record's "Encargados" collection
 * @method Doctrine_Collection getConvocatorias()      Returns the current record's "Convocatorias" collection
 * @method Doctrine_Collection getConvocatoriaCargos() Returns the current record's "ConvocatoriaCargos" collection
 * @method Cargo               setId()                 Sets the current record's "id" value
 * @method Cargo               setCargo()              Sets the current record's "cargo" value
 * @method Cargo               setEncargados()         Sets the current record's "Encargados" collection
 * @method Cargo               setConvocatorias()      Sets the current record's "Convocatorias" collection
 * @method Cargo               setConvocatoriaCargos() Sets the current record's "ConvocatoriaCargos" collection
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCargo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cargo');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('cargo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CargoEncargado as Encargados', array(
             'local' => 'id',
             'foreign' => 'cargo_id'));

        $this->hasMany('Convocatoria as Convocatorias', array(
             'refClass' => 'ConvocatoriaCargo',
             'local' => 'cargo_id',
             'foreign' => 'convocatoria_id'));

        $this->hasMany('ConvocatoriaCargo as ConvocatoriaCargos', array(
             'local' => 'id',
             'foreign' => 'cargo_id'));
    }
}