<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Requisito', 'doctrine');

/**
 * BaseRequisito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $texto
 * @property Doctrine_Collection $Convocatorias
 * @property Doctrine_Collection $ConvocatoriaRequisitos
 * @property Doctrine_Collection $Postulantes
 * @property Doctrine_Collection $PostulanteRequisitos
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getTexto()                  Returns the current record's "texto" value
 * @method Doctrine_Collection getConvocatorias()          Returns the current record's "Convocatorias" collection
 * @method Doctrine_Collection getConvocatoriaRequisitos() Returns the current record's "ConvocatoriaRequisitos" collection
 * @method Doctrine_Collection getPostulantes()            Returns the current record's "Postulantes" collection
 * @method Doctrine_Collection getPostulanteRequisitos()   Returns the current record's "PostulanteRequisitos" collection
 * @method Requisito           setId()                     Sets the current record's "id" value
 * @method Requisito           setTexto()                  Sets the current record's "texto" value
 * @method Requisito           setConvocatorias()          Sets the current record's "Convocatorias" collection
 * @method Requisito           setConvocatoriaRequisitos() Sets the current record's "ConvocatoriaRequisitos" collection
 * @method Requisito           setPostulantes()            Sets the current record's "Postulantes" collection
 * @method Requisito           setPostulanteRequisitos()   Sets the current record's "PostulanteRequisitos" collection
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequisito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('requisito');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Convocatoria as Convocatorias', array(
             'refClass' => 'ConvocatoriaRequisito',
             'local' => 'requisito_id',
             'foreign' => 'convocatoria_id'));

        $this->hasMany('ConvocatoriaRequisito as ConvocatoriaRequisitos', array(
             'local' => 'id',
             'foreign' => 'requisito_id'));

        $this->hasMany('Postulante as Postulantes', array(
             'refClass' => 'PostulanteRequisito',
             'local' => 'requisito_id',
             'foreign' => 'postulante_id'));

        $this->hasMany('PostulanteRequisito as PostulanteRequisitos', array(
             'local' => 'id',
             'foreign' => 'requisito_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}