<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Convocatoria', 'doctrine');

/**
 * BaseConvocatoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property enum $estado
 * 
 * @method integer      getId()     Returns the current record's "id" value
 * @method string       getNombre() Returns the current record's "nombre" value
 * @method enum         getEstado() Returns the current record's "estado" value
 * @method Convocatoria setId()     Sets the current record's "id" value
 * @method Convocatoria setNombre() Sets the current record's "nombre" value
 * @method Convocatoria setEstado() Sets the current record's "estado" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('estado', 'enum', 10, array(
             'type' => 'enum',
             'fixed' => 0,
             'values' => 
             array(
              0 => 'borrador',
              1 => 'emitido',
              2 => 'anulado',
              3 => 'vigente',
              4 => 'finalizado',
              5 => 'eliminado',
             ),
             'default' => 'borrador',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}