<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Requerimiento', 'doctrine');

/**
 * BaseRequerimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $nombre
 * @property string $texto
 * @property integer $horas_academicas
 * @property Doctrine_Collection $Convocatorias
 * @property Doctrine_Collection $ConvocatoriaRequerimientos
 * @property Doctrine_Collection $ConvocatoriaRequerimientoEvaluaciones
 * @property Doctrine_Collection $Requerimiento
 * @property Doctrine_Collection $PostulanteRequerimientos
 * 
 * @method integer             getId()                                    Returns the current record's "id" value
 * @method string              getCodigo()                                Returns the current record's "codigo" value
 * @method string              getNombre()                                Returns the current record's "nombre" value
 * @method string              getTexto()                                 Returns the current record's "texto" value
 * @method integer             getHorasAcademicas()                       Returns the current record's "horas_academicas" value
 * @method Doctrine_Collection getConvocatorias()                         Returns the current record's "Convocatorias" collection
 * @method Doctrine_Collection getConvocatoriaRequerimientos()            Returns the current record's "ConvocatoriaRequerimientos" collection
 * @method Doctrine_Collection getConvocatoriaRequerimientoEvaluaciones() Returns the current record's "ConvocatoriaRequerimientoEvaluaciones" collection
 * @method Doctrine_Collection getRequerimiento()                         Returns the current record's "Requerimiento" collection
 * @method Doctrine_Collection getPostulanteRequerimientos()              Returns the current record's "PostulanteRequerimientos" collection
 * @method Requerimiento       setId()                                    Sets the current record's "id" value
 * @method Requerimiento       setCodigo()                                Sets the current record's "codigo" value
 * @method Requerimiento       setNombre()                                Sets the current record's "nombre" value
 * @method Requerimiento       setTexto()                                 Sets the current record's "texto" value
 * @method Requerimiento       setHorasAcademicas()                       Sets the current record's "horas_academicas" value
 * @method Requerimiento       setConvocatorias()                         Sets the current record's "Convocatorias" collection
 * @method Requerimiento       setConvocatoriaRequerimientos()            Sets the current record's "ConvocatoriaRequerimientos" collection
 * @method Requerimiento       setConvocatoriaRequerimientoEvaluaciones() Sets the current record's "ConvocatoriaRequerimientoEvaluaciones" collection
 * @method Requerimiento       setRequerimiento()                         Sets the current record's "Requerimiento" collection
 * @method Requerimiento       setPostulanteRequerimientos()              Sets the current record's "PostulanteRequerimientos" collection
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRequerimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('requerimiento');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('codigo', 'string', 32, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('nombre', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'default' => '',
             'length' => '',
             ));
        $this->hasColumn('horas_academicas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Convocatoria as Convocatorias', array(
             'refClass' => 'ConvocatoriaRequerimiento',
             'local' => 'requerimiento_id',
             'foreign' => 'convocatoria_id'));

        $this->hasMany('ConvocatoriaRequerimiento as ConvocatoriaRequerimientos', array(
             'local' => 'id',
             'foreign' => 'requerimiento_id'));

        $this->hasMany('ConvocatoriaRequerimientoEvaluacion as ConvocatoriaRequerimientoEvaluaciones', array(
             'local' => 'id',
             'foreign' => 'requerimiento_id'));

        $this->hasMany('Postulante as Requerimiento', array(
             'refClass' => 'PostulanteRequerimiento',
             'local' => 'requerimiento_id',
             'foreign' => 'postulante_id'));

        $this->hasMany('PostulanteRequerimiento as PostulanteRequerimientos', array(
             'local' => 'id',
             'foreign' => 'requerimiento_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}