<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulacionRequisito', 'doctrine');

/**
 * BasePostulacionRequisito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulacion_id
 * @property integer $requisito_id
 * @property Postulacion $Postulacion
 * @property Requisito $Requisito
 * 
 * @method integer              getPostulacionId()  Returns the current record's "postulacion_id" value
 * @method integer              getRequisitoId()    Returns the current record's "requisito_id" value
 * @method Postulacion          getPostulacion()    Returns the current record's "Postulacion" value
 * @method Requisito            getRequisito()      Returns the current record's "Requisito" value
 * @method PostulacionRequisito setPostulacionId()  Sets the current record's "postulacion_id" value
 * @method PostulacionRequisito setRequisitoId()    Sets the current record's "requisito_id" value
 * @method PostulacionRequisito setPostulacion()    Sets the current record's "Postulacion" value
 * @method PostulacionRequisito setRequisito()      Sets the current record's "Requisito" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulacionRequisito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulacion_requisito');
        $this->hasColumn('postulacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requisito_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulacion', array(
             'local' => 'postulacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Requisito', array(
             'local' => 'requisito_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}