<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaNotificacion', 'doctrine');

/**
 * BaseConvocatoriaNotificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property string $cargo
 * @property string $encargado
 * @property string $email
 * @property Convocatoria $Convocatoria
 * 
 * @method integer                  getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method string                   getCargo()           Returns the current record's "cargo" value
 * @method string                   getEncargado()       Returns the current record's "encargado" value
 * @method string                   getEmail()           Returns the current record's "email" value
 * @method Convocatoria             getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method ConvocatoriaNotificacion setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaNotificacion setCargo()           Sets the current record's "cargo" value
 * @method ConvocatoriaNotificacion setEncargado()       Sets the current record's "encargado" value
 * @method ConvocatoriaNotificacion setEmail()           Sets the current record's "email" value
 * @method ConvocatoriaNotificacion setConvocatoria()    Sets the current record's "Convocatoria" value
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaNotificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_notificacion');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('cargo', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('encargado', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}