<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulacionDocumento', 'doctrine');

/**
 * BasePostulacionDocumento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulacion_id
 * @property integer $documento_id
 * @property Postulacion $Postulacion
 * @property Documento $Documento
 * 
 * @method integer              getPostulacionId()  Returns the current record's "postulacion_id" value
 * @method integer              getDocumentoId()    Returns the current record's "documento_id" value
 * @method Postulacion          getPostulacion()    Returns the current record's "Postulacion" value
 * @method Documento            getDocumento()      Returns the current record's "Documento" value
 * @method PostulacionDocumento setPostulacionId()  Sets the current record's "postulacion_id" value
 * @method PostulacionDocumento setDocumentoId()    Sets the current record's "documento_id" value
 * @method PostulacionDocumento setPostulacion()    Sets the current record's "Postulacion" value
 * @method PostulacionDocumento setDocumento()      Sets the current record's "Documento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulacionDocumento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulacion_documento');
        $this->hasColumn('postulacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('documento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulacion', array(
             'local' => 'postulacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Documento', array(
             'local' => 'documento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}