<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Documentacion', 'doctrine');

/**
 * BaseDocumentacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $template_id
 * @property integer $volumen_id
 * @property clob $vars
 * @property DocumentacionVolumen $DocumentacionVolumen
 * 
 * @method integer              getId()                   Returns the current record's "id" value
 * @method integer              getTemplateId()           Returns the current record's "template_id" value
 * @method integer              getVolumenId()            Returns the current record's "volumen_id" value
 * @method clob                 getVars()                 Returns the current record's "vars" value
 * @method DocumentacionVolumen getDocumentacionVolumen() Returns the current record's "DocumentacionVolumen" value
 * @method Documentacion        setId()                   Sets the current record's "id" value
 * @method Documentacion        setTemplateId()           Sets the current record's "template_id" value
 * @method Documentacion        setVolumenId()            Sets the current record's "volumen_id" value
 * @method Documentacion        setVars()                 Sets the current record's "vars" value
 * @method Documentacion        setDocumentacionVolumen() Sets the current record's "DocumentacionVolumen" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('template_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('volumen_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('vars', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             'default' => '',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DocumentacionVolumen', array(
             'local' => 'volumen_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}