<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulanteRequerimiento', 'doctrine');

/**
 * BasePostulanteRequerimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulante_id
 * @property integer $requerimiento_id
 * @property Postulante $Postulante
 * @property Requerimiento $Requerimiento
 * 
 * @method integer                 getPostulanteId()     Returns the current record's "postulante_id" value
 * @method integer                 getRequerimientoId()  Returns the current record's "requerimiento_id" value
 * @method Postulante              getPostulante()       Returns the current record's "Postulante" value
 * @method Requerimiento           getRequerimiento()    Returns the current record's "Requerimiento" value
 * @method PostulanteRequerimiento setPostulanteId()     Sets the current record's "postulante_id" value
 * @method PostulanteRequerimiento setRequerimientoId()  Sets the current record's "requerimiento_id" value
 * @method PostulanteRequerimiento setPostulante()       Sets the current record's "Postulante" value
 * @method PostulanteRequerimiento setRequerimiento()    Sets the current record's "Requerimiento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulanteRequerimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulante_requerimiento');
        $this->hasColumn('postulante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requerimiento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulante', array(
             'local' => 'postulante_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Requerimiento', array(
             'local' => 'requerimiento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}