<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaRequerimiento', 'doctrine');

/**
 * BaseConvocatoriaRequerimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $requerimiento_id
 * @property integer $numero_item
 * @property integer $cantidad_requerida
 * @property Convocatoria $Convocatoria
 * @property Requerimiento $Requerimiento
 * 
 * @method integer                   getConvocatoriaId()     Returns the current record's "convocatoria_id" value
 * @method integer                   getRequerimientoId()    Returns the current record's "requerimiento_id" value
 * @method integer                   getNumeroItem()         Returns the current record's "numero_item" value
 * @method integer                   getCantidadRequerida()  Returns the current record's "cantidad_requerida" value
 * @method Convocatoria              getConvocatoria()       Returns the current record's "Convocatoria" value
 * @method Requerimiento             getRequerimiento()      Returns the current record's "Requerimiento" value
 * @method ConvocatoriaRequerimiento setConvocatoriaId()     Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaRequerimiento setRequerimientoId()    Sets the current record's "requerimiento_id" value
 * @method ConvocatoriaRequerimiento setNumeroItem()         Sets the current record's "numero_item" value
 * @method ConvocatoriaRequerimiento setCantidadRequerida()  Sets the current record's "cantidad_requerida" value
 * @method ConvocatoriaRequerimiento setConvocatoria()       Sets the current record's "Convocatoria" value
 * @method ConvocatoriaRequerimiento setRequerimiento()      Sets the current record's "Requerimiento" value
 * 
 * @package    .
 * @subpackage model
 * @author     Carlos Eduardo Caballero Burgoa
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaRequerimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_requerimiento');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requerimiento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('numero_item', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('cantidad_requerida', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Requerimiento', array(
             'local' => 'requerimiento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}