<?php

/**
 * BaseGrupo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $Permisos
 * @property Doctrine_Collection $Usuarios
 * @property Doctrine_Collection $GrupoPermiso
 * @property UsuarioGrupoConvocatoria $UsuarioGrupoConvocatoria
 * 
 * @method string                   getNombre()                   Returns the current record's "nombre" value
 * @method string                   getDescripcion()              Returns the current record's "descripcion" value
 * @method Doctrine_Collection      getPermisos()                 Returns the current record's "Permisos" collection
 * @method Doctrine_Collection      getUsuarios()                 Returns the current record's "Usuarios" collection
 * @method Doctrine_Collection      getGrupoPermiso()             Returns the current record's "GrupoPermiso" collection
 * @method UsuarioGrupoConvocatoria getUsuarioGrupoConvocatoria() Returns the current record's "UsuarioGrupoConvocatoria" value
 * @method Grupo                    setNombre()                   Sets the current record's "nombre" value
 * @method Grupo                    setDescripcion()              Sets the current record's "descripcion" value
 * @method Grupo                    setPermisos()                 Sets the current record's "Permisos" collection
 * @method Grupo                    setUsuarios()                 Sets the current record's "Usuarios" collection
 * @method Grupo                    setGrupoPermiso()             Sets the current record's "GrupoPermiso" collection
 * @method Grupo                    setUsuarioGrupoConvocatoria() Sets the current record's "UsuarioGrupoConvocatoria" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGrupo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('grupo');
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Permiso as Permisos', array(
             'refClass' => 'GrupoPermiso',
             'local' => 'grupo_id',
             'foreign' => 'permiso_id'));

        $this->hasMany('sfGuardUser as Usuarios', array(
             'refClass' => 'UsuarioGrupo',
             'local' => 'grupo_id',
             'foreign' => 'user_id'));

        $this->hasMany('GrupoPermiso', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $this->hasOne('UsuarioGrupoConvocatoria', array(
             'local' => 'id',
             'foreign' => 'grupo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}