<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PostulanteRequisito', 'doctrine');

/**
 * BasePostulanteRequisito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $postulante_id
 * @property integer $requisito_id
 * @property Postulante $Postulante
 * @property Requisito $Requisito
 * 
 * @method integer             getPostulanteId()  Returns the current record's "postulante_id" value
 * @method integer             getRequisitoId()   Returns the current record's "requisito_id" value
 * @method Postulante          getPostulante()    Returns the current record's "Postulante" value
 * @method Requisito           getRequisito()     Returns the current record's "Requisito" value
 * @method PostulanteRequisito setPostulanteId()  Sets the current record's "postulante_id" value
 * @method PostulanteRequisito setRequisitoId()   Sets the current record's "requisito_id" value
 * @method PostulanteRequisito setPostulante()    Sets the current record's "Postulante" value
 * @method PostulanteRequisito setRequisito()     Sets the current record's "Requisito" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePostulanteRequisito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('postulante_requisito');
        $this->hasColumn('postulante_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('requisito_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Postulante', array(
             'local' => 'postulante_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Requisito', array(
             'local' => 'requisito_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}