<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Documentacion', 'doctrine');

/**
 * BaseDocumentacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $plantilla_id
 * @property integer $volumen_id
 * @property clob $vars
 * @property DocumentacionVolumen $DocumentacionVolumen
 * @property DocumentacionPlantilla $DocumentacionPlantilla
 * 
 * @method integer                getId()                     Returns the current record's "id" value
 * @method integer                getPlantillaId()            Returns the current record's "plantilla_id" value
 * @method integer                getVolumenId()              Returns the current record's "volumen_id" value
 * @method clob                   getVars()                   Returns the current record's "vars" value
 * @method DocumentacionVolumen   getDocumentacionVolumen()   Returns the current record's "DocumentacionVolumen" value
 * @method DocumentacionPlantilla getDocumentacionPlantilla() Returns the current record's "DocumentacionPlantilla" value
 * @method Documentacion          setId()                     Sets the current record's "id" value
 * @method Documentacion          setPlantillaId()            Sets the current record's "plantilla_id" value
 * @method Documentacion          setVolumenId()              Sets the current record's "volumen_id" value
 * @method Documentacion          setVars()                   Sets the current record's "vars" value
 * @method Documentacion          setDocumentacionVolumen()   Sets the current record's "DocumentacionVolumen" value
 * @method Documentacion          setDocumentacionPlantilla() Sets the current record's "DocumentacionPlantilla" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDocumentacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('documentacion');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('plantilla_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('volumen_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'length' => 4,
             ));
        $this->hasColumn('vars', 'clob', null, array(
             'type' => 'clob',
             'fixed' => 0,
             'notnull' => true,
             'default' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DocumentacionVolumen', array(
             'local' => 'volumen_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('DocumentacionPlantilla', array(
             'local' => 'plantilla_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}