<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ConvocatoriaEvaluacion', 'doctrine');

/**
 * BaseConvocatoriaEvaluacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $convocatoria_id
 * @property integer $evaluacion_id
 * @property Convocatoria $Convocatoria
 * @property Evaluacion $Evaluacion
 * 
 * @method integer                getConvocatoriaId()  Returns the current record's "convocatoria_id" value
 * @method integer                getEvaluacionId()    Returns the current record's "evaluacion_id" value
 * @method Convocatoria           getConvocatoria()    Returns the current record's "Convocatoria" value
 * @method Evaluacion             getEvaluacion()      Returns the current record's "Evaluacion" value
 * @method ConvocatoriaEvaluacion setConvocatoriaId()  Sets the current record's "convocatoria_id" value
 * @method ConvocatoriaEvaluacion setEvaluacionId()    Sets the current record's "evaluacion_id" value
 * @method ConvocatoriaEvaluacion setConvocatoria()    Sets the current record's "Convocatoria" value
 * @method ConvocatoriaEvaluacion setEvaluacion()      Sets the current record's "Evaluacion" value
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConvocatoriaEvaluacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('convocatoria_evaluacion');
        $this->hasColumn('convocatoria_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('evaluacion_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Convocatoria', array(
             'local' => 'convocatoria_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Evaluacion', array(
             'local' => 'evaluacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}