default:
  is_secure: true
index:
  credentials:
    - convocatorias_list
new:
  credentials:
    - convocatorias_create
create:
  credentials:
    - convocatorias_create
edit:
  credentials:
    - convocatorias_edit
update:
  credentials:
    - convocatorias_edit
delete:
  credentials:
    - convocatorias_delete
show:
  is_secure: false
texto:
  is_secure: false
latex:
  is_secure: false
pdf:
  is_secure: false
redaccion:
  credentials:
    - convocatorias_edit
eliminar:
  credentials:
    - convocatorias_eliminar
promover:
  credentials:
    - convocatorias_promover
anular:
  credentials:
    - convocatorias_anular
finalizar:
  credentials:
    - convocatorias_finalizar
postular:
  is_secure: false
