default:
  is_secure: true
index:
  credentials:
    - convocatorias_list
new:
  credentials:
    - convocatorias_create
create:
  credentials:
    - convocatorias_create
edit:
  credentials:
    - convocatorias_edit
show:
  is_secure: false
update:
  credentials:
    - convocatorias_edit
delete:
  credentials:
    - convocatorias_delete
texto:
  is_secure: false
latex:
  is_secure: false
pdf:
  is_secure: false
eliminar:
  credentials:
    - convocatorias_eliminar
promover:
  credentials:
    - convocatorias_promover
anular:
  credentials:
    - convocatorias_anular
finalizar:
  credentials:
    - convocatorias_finalizar
redaccion:
  credentials:
    - convocatorias_edit
firmas:
  credentials:
    - convocatorias_edit
notificaciones:
  credentials:
    - convocatorias_edit
cargos:
  credentials:
    - convocatorias_role
eventos:
  credentials:
    - convocatorias_event
postular:
  is_secure: false
