generator:
  class: sfDoctrineGenerator
  param:
    config:
      fields:
        last_name:
          label: Name
        first_name:
          label: Description
      list:
        title: Group list
        display: [name, description, description, description]
        sort: [name, asc]
      filter:
        class: false
      new:
        title: Add a new group
      edit:
        title: Editar "%%name%%"
