<?php

/**
 * CargoEncargadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CargoEncargadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CargoEncargadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CargoEncargado');
    }
}