<?php

/**
 * CartaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CartaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CartaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Carta');
    }
}