<?php

/**
 * ConvocatoriaRequerimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaRequerimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaRequerimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaRequerimiento');
    }
}