<?php

/**
 * ConvocatoriaRedaccionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaRedaccionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaRedaccionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaRedaccion');
    }
}