<?php

/**
 * ConvocatoriaEvaluacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaEvaluacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaEvaluacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaEvaluacion');
    }
}