<?php

/**
 * ConvocatoriaEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ConvocatoriaEvento extends BaseConvocatoriaEvento
{
    public function getPrettyFecha() {
        include_once realpath(dirname(__FILE__) . '/../../../apps/convocatorias/lib/helper/PrettyDateHelper.php');
        return pretty_date($this->_get('fecha'));
    }
}
