<?php

/**
 * ConvocatoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Convocatoria');
    }
}