<?php

/**
 * ConvocatoriaRequerimientoEvaluacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaRequerimientoEvaluacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaRequerimientoEvaluacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaRequerimientoEvaluacion');
    }
}