<?php

/**
 * ConvocatoriaNotificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaNotificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaNotificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaNotificacion');
    }
}