<?php

/**
 * ConvocatoriaRequisitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaRequisitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaRequisitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaRequisito');
    }
}