<?php

/**
 * ConvocatoriaEventoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaEventoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaEventoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaEvento');
    }
}