<?php

/**
 * ConvocatoriaDocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaDocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaDocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaDocumento');
    }
}