<?php

/**
 * ConvocatoriaDocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConvocatoriaDocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConvocatoriaDocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConvocatoriaDocumento');
    }
    
    public function getDocumentos()
     {
        global $c;
        $q = Doctrine_Query::create()
              -> from('Documento d')
              ->innerJoin('d.ConvocatoriaDocumento cd')
              -> where('cd.convocatoria_id = ?', $c);
        return $q->execute();  
     }
}