<?php

/**
 * DocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Documento');
    }
}