<?php

/**
 * DocumentacionPlantillaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentacionPlantillaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentacionPlantillaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentacionPlantilla');
    }
}