<?php

/**
 * DocumentacionVolumenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentacionVolumenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentacionVolumenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentacionVolumen');
    }
}