<?php

/**
 * EvaluacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EvaluacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EvaluacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Evaluacion');
    }
}