<?php

/**
 * GrupoPermisoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GrupoPermisoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GrupoPermisoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GrupoPermiso');
    }
}