<?php

/**
 * PostulacionDocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulacionDocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulacionDocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostulacionDocumento');
    }
}