<?php

/**
 * PostulanteRequerimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulanteRequerimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulanteRequerimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostulanteRequerimiento');
    }
}