<?php

/**
 * PostulanteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulanteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulanteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Postulante');
    }
}