<?php

/**
 * PostulacionRequisitoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulacionRequisitoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulacionRequisitoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostulacionRequisito');
    }
}