<?php

/**
 * PostulacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Postulacion');
    }
}