<?php

/**
 * PostulanteDocumentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulanteDocumentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulanteDocumentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostulanteDocumento');
    }
}