<?php

/**
 * PostulacionRequerimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PostulacionRequerimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PostulacionRequerimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PostulacionRequerimiento');
    }
}