<?php

/**
 * RequerimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RequerimientoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RequerimientoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Requerimiento');
    }
}