<?php

/**
 * UsuarioGrupoConvocatoria
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    .
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class UsuarioGrupoConvocatoria extends BaseUsuarioGrupoConvocatoria
{
    public function getUsuarios($convocatoria, $grupo) {
        $q1 = Doctrine_Query::create()
            ->select('u.user_id')
            ->from('UsuarioGrupoConvocatoria u')
            ->where('u.convocatoria_id = ?', $convocatoria->getId())
            ->andWhere('u.grupo_id = ?', $grupo->getId());
        $array = $q1->fetchArray();

        $users = array();
        foreach ($array as $user) {
            $users[] = $user['user_id'];
        }
        
        $q2 = Doctrine_Core::getTable('sfGuardUser')
          ->createQuery('u')
          ->where('u.id IN (?)', implode(',', $users));

        return $q2->execute();
    }
}
