<?php

/**
 * UsuarioGrupoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioGrupoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioGrupoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioGrupo');
    }
}