<?php

/**
 * UsuarioGrupoConvocatoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioGrupoConvocatoriaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioGrupoConvocatoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioGrupoConvocatoria');
    }
}