all:
  sf_guard_plugin:
    routes_register: false
    allow_login_with_email: false
    signin_form: sfGuardCustomFormSignin
  convocatorias_generator:
    dir_generation: %SF_ROOT_DIR%/data/convocatorias
