all:
  sf_guard_plugin:
    routes_register: false
    allow_login_with_email: false
    signin_form: sfGuardCustomFormSignin
  dir_generation: %SF_ROOT_DIR%/data/convocatorias
  xslt_transforms: %SF_ROOT_DIR%/data/xslt