profile:
  url: /perfil
  param:
    module: portada
    action: perfil

sf_guard_signin:
  url: /acceder
  param:
    module: sfGuardAuth
    action: signin

sf_guard_signout:
  url: /salir
  param:
    module: sfGuardAuth
    action: signout

sf_guard_user:
  url: /usuarios
  param:
    module: sfGuardUser
    action: index

sf_guard_group:
  url: /grupos
  param:
    module: sfGuardGroup
    action: index

sf_guard_permission:
  url: /permisos
  param:
    module: sfGuardPermission
    action: index

sf_guard_forgot_password:
  url: /recuperar
  param:
    module: sfGuardForgotPassword
    action: index

sf_guard_forgot_password_change:
  url: /recuperar/:unique_key
  class: sfDoctrineRoute
  options:
    model: sfGuardForgotPassword
    type: object
  param:
    module: sfGuardForgotPassword
    action: change
  requirements:
    sf_method: [get, post]

convocatorias:
  class: sfDoctrineRouteCollection
  options:
    model: Convocatoria
    actions: [list, new, create, edit, show, update, delete]
    object_actions:
      # document generation
      texto: [get]
      latex: [get]
      pdf: [get]
      # state transition
      eliminar: [post]
      promover: [post]
      anular: [post]
      finalizar: [post]
      # tab functions misc
      redaccion: [post]
      firmas: [post]
      notificaciones: [post]
      cargos: [post]
      eventos: [post]
      # postulations tabs
      postular: [get, post]

requerimientos:
  class: sfDoctrineRouteCollection
  options:
    model: Requerimiento

requisitos:
  class: sfDoctrineRouteCollection
  options:
    model: Requisito

documentos:
  class: sfDoctrineRouteCollection
  options:
    model: Documento

eventos:
  class: sfDoctrineRouteCollection
  options:
    model: Evento

cargos:
  class: sfDoctrineRouteCollection
  options:
    model: Cargo
    object_actions:
      agregar: [get, post]

documentacion:
  class: sfDoctrineRouteCollection
  options:
    model: DocumentacionVolumen
    actions: [list, new, create, show, delete]
    object_actions:
      editar: [post]
      # document generation
      texto: [get]
      latex: [get]
      pdf: [get]

plantillas:
  class: sfDoctrineRouteCollection
  options:
    model:  DocumentacionPlantilla
    object_actions:
      clonar: [post]

postulantes:
  url: /convocatorias/:convocatoria/postulantes.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: list }
  param: { module: postulantes, action: index, sf_format: html }
  requirements: { convocatoria: \d+, sf_method: [get,head] }

postulantes_confirm:
  url: /convocatorias/:convocatoria/postulantes/:id/:hash/confirm.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: object }
  param: { module: postulantes, action: confirm, sf_format: html }
  requirements: { convocatoria: \d+, id: \d+, sf_method: [get,head,post] }

postulantes_edit:
  url: /convocatorias/:convocatoria/postulantes/:id/edit.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: object }
  param: { module: postulantes, action: edit, sf_format: html }
  requirements: { convocatoria: \d+, id: \d+, sf_method: [get,head,post] }

postulantes_delete:
  url: /convocatorias/:convocatoria/postulantes/:id/delete.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: object }
  param:  { module: postulantes, action: delete, sf_format: html }
  requirements: { convocatoria: \d+, id: \d+, sf_method: [delete] }

postulantes_reception:
  url: /convocatorias/:convocatoria/postulantes/:id/reception.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: object }
  param: { module: postulantes, action: reception, sf_format: html }
  requirements: { convocatoria: \d+, id: \d+, sf_method: [get,head,post] }

postulantes_habilitation:
  url: /convocatorias/:convocatoria/postulantes/:id/habilitation.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: object }
  param: { module: postulantes, action: habilitation, sf_format: html }
  requirements: { convocatoria: \d+, id: \d+, sf_method: [get,head,post] }

postulantes_report:
  url: /convocatorias/:convocatoria/postulantes/report.:sf_format
  class: sfDoctrineRoute
  options: { model: Postulante, type: list }
  param: { module: postulantes, action: report, sf_format: html }
  requirements: { convocatoria: \d+, sf_method: [post] }

homepage:
  url: /
  param:
    module: portada
    action: index

default_index:
  url: /:module
  param:
    action: index

default:
  url: /:module/:action/*

#    collection_actions:
#      plantillas: [get]
