sf_guard_signin:
  url: /acceder
  param:
    module: sfGuardAuth
    action: signin

sf_guard_signout:
  url: /salir
  param:
    module: sfGuardAuth
    action: signout

sf_guard_user:
  url: /usuarios
  param:
    module: sfGuardUser
    action: index

sf_guard_group:
  url: /grupos
  param:
    module: sfGuardGroup
    action: index

sf_guard_permission:
  url: /permisos
  param:
    module: sfGuardPermission
    action: index

sf_guard_forgot_password:
  url: /forgot_password
  param:
    module: sfGuardForgotPassword
    action: index

sf_guard_forgot_password_change:
  url: /forgot_password/:unique_key
  class: sfDoctrineRoute
  options:
    model: sfGuardForgotPassword
    type: object
  param:
    module: sfGuardForgotPassword
    action: change
  requirements:
    sf_method: [get, post]

sf_guard_register:
  url: /registro
  param:
    module: sfGuardRegister
    action: index

convocatorias:
  class: sfDoctrineRouteCollection
  options:
    model: Convocatoria
    actions: [list, new, create, edit, update, show, delete]
    collection_actions:
      borradores: [get]
    object_actions:
      texto: [get]
      pdf: [get]
      promover: [post]
      eliminar: [post]
      enmendar: [post]
      anular: [post]
      finalizar: [post]
      redaccion: [post]
      firmas: [post]

requerimientos:
  class: sfDoctrineRouteCollection
  options:
    model: Requerimiento

requisitos:
  class: sfDoctrineRouteCollection
  options:
    model: Requisito

documentos:
  class: sfDoctrineRouteCollection
  options:
    model: Documento

eventos:
  class: sfDoctrineRouteCollection
  options:
    model: Evento

cargos:
  class: sfDoctrineRouteCollection
  options:
    model: Cargo
    object_actions:
      agregar: [get, post]

homepage:
  url: /
  param:
    module: portada
    action: index

default_index:
  url: /:module
  param:
    action: index

default:
  url: /:module/:action/*
