# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

convocatorias:
  class: sfDoctrineRouteCollection
  options:
    model: Convocatoria
    actions: [list, new, create, edit, update, delete, show]
    collection_actions:
      borradores: [get]
    object_actions:
      toggle: [put]

# default rules
homepage:
  url:   /
  param: { module: portada, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
