# sfGuardAuth
sf_guard_signin:
  url: /acceder
  param: { module: sfGuardAuth, action: signin}

sf_guard_signout:
  url: /salir
  param: {module: sfGuardAuth, action: signout}

# sfGuardUser
sf_guard_user:
  url: /usuarios
  param: {module: sfGuardUser, action: index}

# sfGuardGroup
sf_guard_group:
  url: /grupos
  param: {module: sfGuardGroup, action: index}

# sfGuardPermission
sf_guard_permission:
  url: /permisos
  param: {module: sfGuardPermission, action: index}

#sf_guard_forgot_password:
#  url: /forgot_password
#  param: {module: sfGuardForgotPassword, action: index}
#
#sf_guard_groupRegister:
#  url: /roles
#  param: {module: sfGuardGroup, action: groupRegister}
#
#sf_guard_register:
#  url: /registro
#  param: {module: sfGuardRegister, action: index}
#

# routing for convocatorias
convocatorias:
  class: sfDoctrineRouteCollection
  options:
    model: Convocatoria
    actions:
      - list
      - new
      - create
      - edit
      - update
      - show
      - delete
    collection_actions:
      borradores: [get]
    object_actions:
      texto: [get]
      pdf: [get]
      promover: [post]
      eliminar: [post]
      enmendar: [post]
      anular: [post]
      finalizar: [post]
      redaccion: [post]

requerimientos:
  class: sfDoctrineRouteCollection
  options: { model: Requerimiento }

requisitos:
  class: sfDoctrineRouteCollection
  options: { model: Requisito }

documentos:
  class: sfDoctrineRouteCollection
  options: { model: Documento }

eventos:
  class: sfDoctrineRouteCollection
  options: { model: Evento }

cargos:
  class: sfDoctrineRouteCollection
  options: { model: Cargo }

# default rules
homepage:
  url:   /
  param: { module: portada, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
