prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              false
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            ce43c4693a5bc46e1902003b9cffefa7b7b0a3a6
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS
    # Enable the database manager
    use_database:           true
    # Helpers used by system
    standard_helpers:
      - Partial
      - PrettyDate
      - I18N
      - UserSelector
      - ImageState
      - SpecialEscape
    #Form helper is out!.
    i18n: true
    default_culture: es_BO
    charset: utf-8
    # Modules needed for authentification
    enabled_modules:
      - default
      - sfGuardAuth
      - sfGuardUser
      - sfGuardGroup
      - sfGuardPermission
      - sfGuardForgotPassword
      #- sfGuardRegister
    # Settings for sfDoctrineGuardPlugin
    login_module: sfGuardAuth
    login_action: signin
    secure_module: sfGuardAuth
    secure_action: secure
