default:
  http_metas:
    content-type: text/html; charset=utf-8

  metas:
    title: vocare
    description: sistema para el lanzamiento de convocatorias en el departamento de informática y sistemas
    keywords: vocare, cidetsi, convocatorias
    language: es
    robots: index, follow

  stylesheets:
   - main.css
   - convocatorias.css
   - letters.css
   - boxes.css
   - smoothness/jquery-ui-1.10.1.custom.min.css

  javascripts:
    - jquery-1.9.0.min.js
    - jquery-ui-1.10.1.custom.min.js
    - format.js
    - Box/boxes.js
    - Box/behaviors.js
    - Box/menu.js
    - Box/manager.js
    - convocatorias.js

  has_layout: true
  layout: layout
