default:
  is_secure: true
index:
  is_secure: false
error404:
  is_secure: false
convocatorias:
  is_secure: false
plantillas:
  credentials:
    - plantillas_list
personas:
  credentials:
    - usuarios_list
