Requisito:
  actAs: [Timestampable]
  connection: doctrine
  tableName: requisito
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    texto:
      type: string()
      fixed: false
      notnull: true
