Evaluacion:
  actAs: [Timestampable]
  connection: doctrine
  tableName: evaluacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nombre:
      type: string()
      fixed: false
      notnull: true
    nombre_corto:
      type: string(128)
      fixed: false
      notnull: true
      
#Evaluacion:
#  actAs:
#    Timestampable:
#    NestedSet:
#      asManyRoots: true
#      rootColumnsName: root
#  connection: doctrine
#  tableName: evaluacion
#  columns:
#    id:
#      type: integer(4)
#      fixed: false
#      unsigned: true
#      primary: true
#      autoincrement: true
#    nombre:
#      type: string(256)
#      fixed: false
#      unsigned: false
#      primary: false
#      notnull: true
#      autoincrement: false
#    minimo:
#      type: integer(4)
#      fixed: false
#      unsigned: false
#      primary: false
#      default: 0
#      notnull: true
#      autoincrement: false
#    maximo:
#      type: integer(4)
#      fixed: false
#      unsigned: false
#      primary: false
#      default: 100
#      notnull: true
#      autoincrement: false
#    omision:
#      type: integer(4)
#      fixed: false
#      unsigned: false
#      default: 0
#      primary: false
#      notnull: true
#      autoincrement: false
#    formula:
#      type: string(1024)
#      fixed: false
#      unsigned: false
#      primary: false
#      default: ''
#      notnull: true
#      autoincrement: false
      