Cargo:
  connection: doctrine
  tableName: cargo
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    cargo:
      type: string(255)
      fixed: false
      notnull: true
  relations:
    Encargados:
      class: CargoEncargado
      local: id
      foreign: cargo_id
      type: many

CargoEncargado:
  connection: doctrine
  tableName: cargo_encargado
  columns:
    cargo_id:
      type: integer(4)
      fixed: false
      unsigned: true
    encargado:
      type: string(255)
      fixed: false
      notnull: true
    email:
      type: string(255)
      fixed: false
      notnull: false
    fecha:
      type: date
      fixed: false
      notnull: true
  relations:
    Cargo:
      local: cargo_id
      foreign: id
      onDelete: cascade
