Convocatoria:
  actAs: [Timestampable]
  connection: doctrine
  tableName: convocatoria
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    gestion:
      type: string(255)
      fixed: false
      notnull: true
    estado:
      type: enum(10)
      fixed: false
      values:
        - borrador
        - emitido
        - anulado
        - vigente
        - finalizado
        - eliminado
      default: borrador
      notnull: true
    publicacion:
      type: date
      fixed: false
      notnull: true
  relations:
    Redacciones:
      class: ConvocatoriaRedaccion
      local: id
      foreign: convocatoria_id
      type: many
    Requerimientos:
      class: Requerimiento
      refClass: ConvocatoriaRequerimiento
      foreignAlias: Convocatorias
    Requisitos:
      class: Requisito
      refClass: ConvocatoriaRequisito
      foreignAlias: Convocatorias
    Documentos:
      class: Documento
      refClass: ConvocatoriaDocumento
      foreignAlias: Convocatorias
    Eventos:
      class: Evento
      refClass: ConvocatoriaEvento
      foreignAlias: Convocatorias
    Evaluaciones:
      class: Evaluacion
      refClass: ConvocatoriaEvaluacion
      foreignAlias: Convocatorias
    Cargos:
      class: Cargo
      refClass: ConvocatoriaCargo
      foreignAlias: Convocatorias
    Notificaciones:
      class: ConvocatoriaNotificacion
      local: id
      foreign: convocatoria_id
      type: many
    Postulantes:
      class: Postulante
      local: id
      foreign: convocatoria_id
      type: many

ConvocatoriaRequerimiento:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_requerimiento
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requerimiento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    numero_item:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 0
    cantidad_requerida:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 0
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaRequerimientos
      onDelete: CASCADE
    Requerimiento:
      foreignAlias: ConvocatoriaRequerimientos
      onDelete: CASCADE

ConvocatoriaRequisito:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_requisito
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requisito_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    numero_orden:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 0
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaRequisitos
      onDelete: CASCADE
    Requisito:
      foreignAlias: ConvocatoriaRequisitos
      onDelete: CASCADE

ConvocatoriaDocumento:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_documento
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    documento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    numero_orden:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 0
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaDocumentos
      onDelete: CASCADE
    Documento:
      foreignAlias: ConvocatoriaDocumentos
      onDelete: CASCADE

ConvocatoriaEvento:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_evento
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    evento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    fecha:
      type: date
      fixed: false
      notnull: true
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaEventos
      onDelete: CASCADE
    Evento:
      foreignAlias: ConvocatoriaEventos
      onDelete: CASCADE

ConvocatoriaEvaluacion:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_evaluacion
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    evaluacion_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaEvaluaciones
      onDelete: CASCADE
    Evaluacion:
      foreignAlias: ConvocatoriaEvaluaciones
      onDelete: CASCADE

ConvocatoriaRequerimientoEvaluacion:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_requerimiento_evaluacion
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requerimiento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    evaluacion_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaRequerimientoEvaluaciones
      onDelete: CASCADE
    Requerimiento:
      foreignAlias: ConvocatoriaRequerimientoEvaluaciones
      onDelete: CASCADE
    Evaluacion:
      foreignAlias: ConvocatoriaRequerimientoEvaluaciones
      onDelete: CASCADE

ConvocatoriaRedaccion:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_redaccion
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
    numero_enmienda:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 1
    redaccion:
      type: clob
      fixed: false
      notnull: true
      default: ''
  relations:
    Convocatoria:
      local: convocatoria_id
      foreign: id
      onDelete: cascade

ConvocatoriaCargo:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_cargo
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    cargo_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    numero_orden:
      type: integer(4)
      fixed: false
      unsigned: true
      notnull: true
      default: 0
  relations:
    Convocatoria:
      foreignAlias: ConvocatoriaCargos
      onDelete: CASCADE
    Cargo:
      foreignAlias: ConvocatoriaCargos
      onDelete: CASCADE

ConvocatoriaNotificacion:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: convocatoria_notificacion
  columns:
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
    cargo:
      type: string(255)
      fixed: false
      notnull: true
    encargado:
      type: string(255)
      fixed: false
      notnull: true
    email:
      type: string(255)
      fixed: false
      notnull: true
  relations:
    Convocatoria:
      local: convocatoria_id
      foreign: id
      onDelete: cascade
