DocumentacionPlantilla:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion_plantilla
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      notnull: true
    redaccion:
      type: clob
      fixed: false
      notnull: true
      default: ''
    types:
      type: clob
      fixed: false
      notnull: true
      default: ''
  relations:
    Volumenes:
      class: DocumentacionVolumen
      local: id
      foreign: plantilla_id
      type: many

DocumentacionVolumen:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion_volumen
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    plantilla_id:
      type: integer(4)
      fixed: false
      unsigned: true
  relations:
    Plantilla:
      local: plantilla_id
      foreign: id
      onDelete: cascade
    Documentaciones:
      class: Documentacion
      local: id
      foreign: volumen_id
      type: many

Documentacion:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    plantilla_id:
      type: integer(4)
      fixed: false
      unsigned: true
    volumen_id:
      type: integer(4)
      fixed: false
      unsigned: true
    vars:
      type: clob
      fixed: false
      notnull: true
      default: ''
  relations:
    Plantilla:
      local: plantilla_id
      foreign: id
      onDelete: cascade
    Volumen:
      local: volumen_id
      foreign: id
      onDelete: cascade
