Plantilla:
  actAs: [Timestampable]
  connection: doctrine
  tableName: plantilla
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      notnull: true
    redaccion:
      type: clob
      fixed: false
      notnull: true
      default: ''
    types:
      type: clob
      fixed: false
      notnull: true
      default: ''

Documentacion:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    nombre:
      type: string(128)
      fixed: false
      notnull: true
    redaccion:
      type: clob
      fixed: false
      notnull: true
      default: ''
    vars:
      type: clob
      fixed: false
      notnull: true
      default: ''
