DocumentacionPlantilla:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion_plantilla
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    label:
      type: string(128)
      notnull: true
    redaction:
      type: clob
      notnull: true
      default: ''
    types:
      type: clob
      notnull: true
      default: ''
  relations:
    Volumenes:
      class: DocumentacionVolumen
      local: id
      foreign: template_id
      type: many

DocumentacionVolumen:
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion_volumen
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    template_id:
      type: integer(4)
      unsigned: true
      primary: false
    label:
      type: string(128)
      notnull: true
    vars:
      type: clob
      notnull: true
      default: ''
  relations:
    Template:
      local: template_id
      foreign: id
      foreignAlias: Volumenes
      foreignType: many
      type: one
    Documents:
      class: Documentacion
      local: id
      foreign: volumen_id
      type: many

Documentacion:
  options:
    symfony:
      form: false
      filter: false
  actAs: [Timestampable]
  connection: doctrine
  tableName: documentacion
  columns:
    id:
      type: integer(4)
      unsigned: true
      primary: true
      autoincrement: true
    template_id:
      type: integer(4)
      unsigned: true
      primary: true
    volumen_id:
      type: integer(4)
      unsigned: true
      primary: true
    vars:
      type: clob
      notnull: true
      default: ''
  relations:
    Volumen:
      local: volumen_id
      foreign: id
      foreignAlias: Documents
      foreignType: many
      type: one
