Postulante:
  actAs: [Timestampable]
  connection: doctrine
  tableName: postulante
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
    apellido_paterno:
      type: string(32)
      fixed: false
      notnull: true
    apellido_materno:
      type: string(32)
      fixed: false
      notnull: true
      default: ''
    nombres:
      type: string(32)
      fixed: false
      notnull: true
    ci:
      type: string(16)
      fixed: false
      notnull: true
    sis:
      type: string(9)
      fixed: false
      notnull: true
    correo_electronico:
      type: string(255)
      fixed: false
      notnull: true
    telefono:
      type: string(32)
      fixed: false
      notnull: true
      default: ''
    direccion:
      type: string(32)
      fixed: false
      notnull: true
      default: ''
    numero_hojas:
      type: integer(4)
      unsigned: true
      fixed: false
      notnull: true
      default: 0
    fecha_entrega:
      type: datetime
      fixed: false
      notnull: false
    estado:
      type: enum(12)
      fixed: false
      values:
        - pendiente
        - inscrito
        - inhabilitado
        - habilitado
      default: pendiente
      notnull: true
    observacion:
      type: string()
      fixed: false
      notnull: true
      default: ''
  relations:
    Convocatoria:
      class: Convocatoria
      local: convocatoria_id
      foreign: id
      foreignAlias: Convocatoria
      foreignType: many
      type: one
    Requerimientos:
      class: Requerimiento
      refClass: PostulanteRequerimiento
      foreignAlias: Postulantes
    Requisitos:
      class: Requisito
      refClass: PostulanteRequisito
      foreignAlias: Postulantes
    Documentos:
      class: Documento
      refClass: PostulanteDocumento
      foreignAlias: Postulantes

PostulanteRequerimiento:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: postulante_requerimiento
  columns:
    postulante_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requerimiento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulante:
      foreignAlias: PostulanteRequerimientos
      onDelete: CASCADE
    Requerimiento:
      foreignAlias: PostulanteRequerimientos
      onDelete: CASCADE

PostulanteRequisito:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: postulante_requisito
  columns:
    postulante_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requisito_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulante:
      foreignAlias: PostulanteRequisitos
      onDelete: CASCADE
    Requisito:
      foreignAlias: PostulanteRequisitos
      onDelete: CASCADE

PostulanteDocumento:
  options:
    symfony:
      form: false
      filter: false
  connection: doctrine
  tableName: postulante_documento
  columns:
    postulante_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    documento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulante:
      foreignAlias: PostulanteDocumentos
      onDelete: CASCADE
    Documento:
      foreignAlias: PostulanteDocumentos
      onDelete: CASCADE
