Postulacion:
  actAs: [Timestampable]
  connection: doctrine
  tableName: postulacion
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
      autoincrement: true
    user_id:
      type: integer
      primary: true
    convocatoria_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    ci:
      type: string(16)
      fixed: false
      notnull: true
    cod_sis:
      type: string(9)
      fixed: false
      notnull: true
    telefono:
      type: string(32)
      fixed: false
      notnull: true
      default: ''
    direccion:
      type: string(32)
      fixed: false
      notnull: true
      default: ''
    numero_hojas:
      type: integer(4)
      unsigned: true
      fixed: false
      notnull: true
      default: 0
    estado:
      type: enum(12)
      fixed: false
      values:
        - pendiente
        - inscrito
        - inhabilitado
        - habilitado
      default: pendiente
      notnull: true
    observacion:
      type: string()
      fixed: false
      notnull: true
      default: ''
  relations:
    User:
      class: sfGuardUser
      local: user_id
      foreign: id
      foreignType: one
      type: many
    Convocatoria:
      class: Convocatoria
      local: convocatoria_id
      foreign: id
      foreignAlias: Convocatoria
      foreignType: one
      type: many
    Requerimiento:
      class: Requerimiento
      refClass: PostulacionRequerimiento
      foreignAlias: Requerimiento
    Requisito:
      class: Requisito
      refClass: PostulacionRequisito
      foreignAlias: Requisito
    Documento:
      class: Documento
      refClass: PostulacionDocumento
      foreignAlias: Documento

PostulacionRequerimiento:
  connection: doctrine
  tableName: postulacion_requerimiento
  columns:
    postulacion_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requerimiento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulacion:
      foreignAlias: PostulacionRequerimientos
      onDelete: CASCADE
    Requerimiento:
      foreignAlias: PostulacionRequerimientos
      onDelete: CASCADE

PostulacionRequisito:
  connection: doctrine
  tableName: postulacion_requisito
  columns:
    postulacion_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    requisito_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulacion:
      foreignAlias: PostulacionRequisito
      onDelete: CASCADE
    Requisito:
      foreignAlias: PostulacionRequisito
      onDelete: CASCADE

PostulacionDocumento:
  connection: doctrine
  tableName: postulacion_documento
  columns:
    postulacion_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
    documento_id:
      type: integer(4)
      fixed: false
      unsigned: true
      primary: true
  relations:
    Postulacion:
      foreignAlias: PostulacionDocumento
      onDelete: CASCADE
    Documento:
      foreignAlias: PostulacionDocumento
      onDelete: CASCADE
